//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public string Borrower { get; set; }
        public Nullable<System.DateTime> DateOfBorrow { get; set; }
    }
}
